[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 120 wsgi:application"

